def normalize_brand_name(brand):
    mapping = {
        'Barn': 'The Barn',
        'Dak': 'DAK Coffee Roasters',
        'Ethica': 'Ethica Coffee Roasters',
        'Firebat': 'Firebat Coffee Roasters',
        'Hasty': 'Hasty Coffee',
        'Hatch': 'Hatch Coffee Roasters',
        'House of Funk': 'House of Funk Brewing Co',
        'Keen': 'Keen Coffee',
        'Loquat': 'Loquat Coffee',
        'Manhattan': 'Manhattan Coffee Roasters',
        'Monogram': 'Monogram Coffee',
        'Onyx': 'Onyx Coffee Lab',
        'Prodigal': 'Prodigal Coffee',
        'Proud Mary': 'Proud Mary Coffee Roasters',
        'September': 'September Coffee Co',
        'Rabbit Hole': 'Rabbit Hole Roasters',
        'Resident': 'Resident Coffee Roasters',
        'Roasti': 'Roasti Coffee',
        'Rooftop': 'Rooftop Coffee Roasters',
        'Sloane': 'Sloane Coffee',
        'Sorellina': 'Sorellina Coffee',
        'Thom Bargen': 'Thom Bargen Coffee Roasters',
        'Traffic': 'Traffic Coffee',
        'Transcend': 'Transcend Coffee',
        'Valor': 'Valor Coffee',
    }

    return mapping.get(brand, brand)
