-- Seed the `continent` table
INSERT INTO continent (name) VALUES
('Africa'),
('Antarctica'),
('Asia'),
('Europe'),
('North America'),
('Oceania'),
('South America'),
('Unknown')
ON CONFLICT (name) DO NOTHING;

-- Seed the `product_type` table
INSERT INTO product_type (name) VALUES
('Roasted Whole Bean'),
('Green Whole Bean'),
('Instant'),
('Capsule'),
('Unknown')
ON CONFLICT (name) DO NOTHING;

-- Seed the `process_category` table
INSERT INTO process_category (name) VALUES
('Washed'),
('Natural'),
('Honey'),
('Experimental'),
('Unknown')
ON CONFLICT (name) DO NOTHING;

-- Seed the `currency_code` table
INSERT INTO currency_code (code) VALUES
('CAD'),
('USD')
ON CONFLICT (code) DO NOTHING;

-- Seed the country table
INSERT INTO country (name, continent_id) VALUES
('Aruba', (SELECT id FROM continent WHERE name = 'North America')),
('Afghanistan', (SELECT id FROM continent WHERE name = 'Asia')),
('Angola', (SELECT id FROM continent WHERE name = 'Africa')),
('Anguilla', (SELECT id FROM continent WHERE name = 'North America')),
('�land Islands', (SELECT id FROM continent WHERE name = 'Europe')),
('Albania', (SELECT id FROM continent WHERE name = 'Europe')),
('Andorra', (SELECT id FROM continent WHERE name = 'Europe')),
('United Arab Emirates', (SELECT id FROM continent WHERE name = 'Asia')),
('Argentina', (SELECT id FROM continent WHERE name = 'South America')),
('Armenia', (SELECT id FROM continent WHERE name = 'Asia')),
('American Samoa', (SELECT id FROM continent WHERE name = 'Oceania')),
('Antigua and Barbuda', (SELECT id FROM continent WHERE name = 'North America')),
('Australia', (SELECT id FROM continent WHERE name = 'Oceania')),
('Austria', (SELECT id FROM continent WHERE name = 'Europe')),
('Azerbaijan', (SELECT id FROM continent WHERE name = 'Asia')),
('Burundi', (SELECT id FROM continent WHERE name = 'Africa')),
('Belgium', (SELECT id FROM continent WHERE name = 'Europe')),
('Benin', (SELECT id FROM continent WHERE name = 'Africa')),
('Bonaire, Sint Eustatius and Saba', (SELECT id FROM continent WHERE name = 'North America')),
('Burkina Faso', (SELECT id FROM continent WHERE name = 'Africa')),
('Bangladesh', (SELECT id FROM continent WHERE name = 'Asia')),
('Bulgaria', (SELECT id FROM continent WHERE name = 'Europe')),
('Bahrain', (SELECT id FROM continent WHERE name = 'Asia')),
('Bahamas', (SELECT id FROM continent WHERE name = 'North America')),
('Bosnia and Herzegovina', (SELECT id FROM continent WHERE name = 'Europe')),
('Saint Barth�lemy', (SELECT id FROM continent WHERE name = 'North America')),
('Belarus', (SELECT id FROM continent WHERE name = 'Europe')),
('Belize', (SELECT id FROM continent WHERE name = 'North America')),
('Bermuda', (SELECT id FROM continent WHERE name = 'North America')),
('Bolivia, Plurinational State of', (SELECT id FROM continent WHERE name = 'South America')),
('Brazil', (SELECT id FROM continent WHERE name = 'South America')),
('Barbados', (SELECT id FROM continent WHERE name = 'North America')),
('Brunei Darussalam', (SELECT id FROM continent WHERE name = 'Asia')),
('Bhutan', (SELECT id FROM continent WHERE name = 'Asia')),
('Bouvet Island', (SELECT id FROM continent WHERE name = 'Antarctica')),
('Botswana', (SELECT id FROM continent WHERE name = 'Africa')),
('Central African Republic', (SELECT id FROM continent WHERE name = 'Africa')),
('Canada', (SELECT id FROM continent WHERE name = 'North America')),
('Cocos (Keeling) Islands', (SELECT id FROM continent WHERE name = 'Asia')),
('Switzerland', (SELECT id FROM continent WHERE name = 'Europe')),
('Chile', (SELECT id FROM continent WHERE name = 'South America')),
('China', (SELECT id FROM continent WHERE name = 'Asia')),
('C�te d''Ivoire', (SELECT id FROM continent WHERE name = 'Africa')),
('Cameroon', (SELECT id FROM continent WHERE name = 'Africa')),
('Congo, The Democratic Republic of the', (SELECT id FROM continent WHERE name = 'Africa')),
('Congo', (SELECT id FROM continent WHERE name = 'Africa')),
('Cook Islands', (SELECT id FROM continent WHERE name = 'Oceania')),
('Colombia', (SELECT id FROM continent WHERE name = 'South America')),
('Comoros', (SELECT id FROM continent WHERE name = 'Africa')),
('Cabo Verde', (SELECT id FROM continent WHERE name = 'Africa')),
('Costa Rica', (SELECT id FROM continent WHERE name = 'North America')),
('Cuba', (SELECT id FROM continent WHERE name = 'North America')),
('Cura�ao', (SELECT id FROM continent WHERE name = 'North America')),
('Christmas Island', (SELECT id FROM continent WHERE name = 'Asia')),
('Cayman Islands', (SELECT id FROM continent WHERE name = 'North America')),
('Cyprus', (SELECT id FROM continent WHERE name = 'Asia')),
('Czechia', (SELECT id FROM continent WHERE name = 'Europe')),
('Germany', (SELECT id FROM continent WHERE name = 'Europe')),
('Djibouti', (SELECT id FROM continent WHERE name = 'Africa')),
('Dominica', (SELECT id FROM continent WHERE name = 'North America')),
('Denmark', (SELECT id FROM continent WHERE name = 'Europe')),
('Dominican Republic', (SELECT id FROM continent WHERE name = 'North America')),
('Algeria', (SELECT id FROM continent WHERE name = 'Africa')),
('Ecuador', (SELECT id FROM continent WHERE name = 'South America')),
('Egypt', (SELECT id FROM continent WHERE name = 'Africa')),
('Eritrea', (SELECT id FROM continent WHERE name = 'Africa')),
('Spain', (SELECT id FROM continent WHERE name = 'Europe')),
('Estonia', (SELECT id FROM continent WHERE name = 'Europe')),
('Ethiopia', (SELECT id FROM continent WHERE name = 'Africa')),
('Finland', (SELECT id FROM continent WHERE name = 'Europe')),
('Fiji', (SELECT id FROM continent WHERE name = 'Oceania')),
('Falkland Islands (Malvinas)', (SELECT id FROM continent WHERE name = 'South America')),
('France', (SELECT id FROM continent WHERE name = 'Europe')),
('Faroe Islands', (SELECT id FROM continent WHERE name = 'Europe')),
('Micronesia, Federated States of', (SELECT id FROM continent WHERE name = 'Oceania')),
('Gabon', (SELECT id FROM continent WHERE name = 'Africa')),
('United Kingdom', (SELECT id FROM continent WHERE name = 'Europe')),
('Georgia', (SELECT id FROM continent WHERE name = 'Asia')),
('Guernsey', (SELECT id FROM continent WHERE name = 'Europe')),
('Ghana', (SELECT id FROM continent WHERE name = 'Africa')),
('Gibraltar', (SELECT id FROM continent WHERE name = 'Europe')),
('Guinea', (SELECT id FROM continent WHERE name = 'Africa')),
('Guadeloupe', (SELECT id FROM continent WHERE name = 'North America')),
('Gambia', (SELECT id FROM continent WHERE name = 'Africa')),
('Guinea-Bissau', (SELECT id FROM continent WHERE name = 'Africa')),
('Equatorial Guinea', (SELECT id FROM continent WHERE name = 'Africa')),
('Greece', (SELECT id FROM continent WHERE name = 'Europe')),
('Grenada', (SELECT id FROM continent WHERE name = 'North America')),
('Greenland', (SELECT id FROM continent WHERE name = 'North America')),
('Guatemala', (SELECT id FROM continent WHERE name = 'North America')),
('French Guiana', (SELECT id FROM continent WHERE name = 'South America')),
('Guam', (SELECT id FROM continent WHERE name = 'Oceania')),
('Guyana', (SELECT id FROM continent WHERE name = 'South America')),
('Hong Kong', (SELECT id FROM continent WHERE name = 'Asia')),
('Heard Island and McDonald Islands', (SELECT id FROM continent WHERE name = 'Antarctica')),
('Honduras', (SELECT id FROM continent WHERE name = 'North America')),
('Croatia', (SELECT id FROM continent WHERE name = 'Europe')),
('Haiti', (SELECT id FROM continent WHERE name = 'North America')),
('Hungary', (SELECT id FROM continent WHERE name = 'Europe')),
('Indonesia', (SELECT id FROM continent WHERE name = 'Asia')),
('Isle of Man', (SELECT id FROM continent WHERE name = 'Europe')),
('India', (SELECT id FROM continent WHERE name = 'Asia')),
('British Indian Ocean Territory', (SELECT id FROM continent WHERE name = 'Asia')),
('Ireland', (SELECT id FROM continent WHERE name = 'Europe')),
('Iran, Islamic Republic of', (SELECT id FROM continent WHERE name = 'Asia')),
('Iraq', (SELECT id FROM continent WHERE name = 'Asia')),
('Iceland', (SELECT id FROM continent WHERE name = 'Europe')),
('Israel', (SELECT id FROM continent WHERE name = 'Asia')),
('Italy', (SELECT id FROM continent WHERE name = 'Europe')),
('Jamaica', (SELECT id FROM continent WHERE name = 'North America')),
('Jersey', (SELECT id FROM continent WHERE name = 'Europe')),
('Jordan', (SELECT id FROM continent WHERE name = 'Asia')),
('Japan', (SELECT id FROM continent WHERE name = 'Asia')),
('Kazakhstan', (SELECT id FROM continent WHERE name = 'Asia')),
('Kenya', (SELECT id FROM continent WHERE name = 'Africa')),
('Kyrgyzstan', (SELECT id FROM continent WHERE name = 'Asia')),
('Cambodia', (SELECT id FROM continent WHERE name = 'Asia')),
('Kiribati', (SELECT id FROM continent WHERE name = 'Oceania')),
('Saint Kitts and Nevis', (SELECT id FROM continent WHERE name = 'North America')),
('Korea, Republic of', (SELECT id FROM continent WHERE name = 'Asia')),
('Kuwait', (SELECT id FROM continent WHERE name = 'Asia')),
('Lao People''s Democratic Republic', (SELECT id FROM continent WHERE name = 'Asia')),
('Lebanon', (SELECT id FROM continent WHERE name = 'Asia')),
('Liberia', (SELECT id FROM continent WHERE name = 'Africa')),
('Libya', (SELECT id FROM continent WHERE name = 'Africa')),
('Saint Lucia', (SELECT id FROM continent WHERE name = 'North America')),
('Liechtenstein', (SELECT id FROM continent WHERE name = 'Europe')),
('Sri Lanka', (SELECT id FROM continent WHERE name = 'Asia')),
('Lesotho', (SELECT id FROM continent WHERE name = 'Africa')),
('Lithuania', (SELECT id FROM continent WHERE name = 'Europe')),
('Luxembourg', (SELECT id FROM continent WHERE name = 'Europe')),
('Latvia', (SELECT id FROM continent WHERE name = 'Europe')),
('Macao', (SELECT id FROM continent WHERE name = 'Asia')),
('Saint Martin (French part)', (SELECT id FROM continent WHERE name = 'North America')),
('Morocco', (SELECT id FROM continent WHERE name = 'Africa')),
('Monaco', (SELECT id FROM continent WHERE name = 'Europe')),
('Moldova, Republic of', (SELECT id FROM continent WHERE name = 'Europe')),
('Madagascar', (SELECT id FROM continent WHERE name = 'Africa')),
('Maldives', (SELECT id FROM continent WHERE name = 'Asia')),
('Mexico', (SELECT id FROM continent WHERE name = 'North America')),
('Marshall Islands', (SELECT id FROM continent WHERE name = 'Oceania')),
('North Macedonia', (SELECT id FROM continent WHERE name = 'Europe')),
('Mali', (SELECT id FROM continent WHERE name = 'Africa')),
('Malta', (SELECT id FROM continent WHERE name = 'Europe')),
('Myanmar', (SELECT id FROM continent WHERE name = 'Asia')),
('Montenegro', (SELECT id FROM continent WHERE name = 'Europe')),
('Mongolia', (SELECT id FROM continent WHERE name = 'Asia')),
('Northern Mariana Islands', (SELECT id FROM continent WHERE name = 'Oceania')),
('Mozambique', (SELECT id FROM continent WHERE name = 'Africa')),
('Mauritania', (SELECT id FROM continent WHERE name = 'Africa')),
('Montserrat', (SELECT id FROM continent WHERE name = 'North America')),
('Martinique', (SELECT id FROM continent WHERE name = 'North America')),
('Mauritius', (SELECT id FROM continent WHERE name = 'Africa')),
('Malawi', (SELECT id FROM continent WHERE name = 'Africa')),
('Malaysia', (SELECT id FROM continent WHERE name = 'Asia')),
('Mayotte', (SELECT id FROM continent WHERE name = 'Africa')),
('Namibia', (SELECT id FROM continent WHERE name = 'Africa')),
('New Caledonia', (SELECT id FROM continent WHERE name = 'Oceania')),
('Niger', (SELECT id FROM continent WHERE name = 'Africa')),
('Norfolk Island', (SELECT id FROM continent WHERE name = 'Oceania')),
('Nigeria', (SELECT id FROM continent WHERE name = 'Africa')),
('Nicaragua', (SELECT id FROM continent WHERE name = 'North America')),
('Niue', (SELECT id FROM continent WHERE name = 'Oceania')),
('Netherlands', (SELECT id FROM continent WHERE name = 'Europe')),
('Norway', (SELECT id FROM continent WHERE name = 'Europe')),
('Nepal', (SELECT id FROM continent WHERE name = 'Asia')),
('Nauru', (SELECT id FROM continent WHERE name = 'Oceania')),
('New Zealand', (SELECT id FROM continent WHERE name = 'Oceania')),
('Oman', (SELECT id FROM continent WHERE name = 'Asia')),
('Pakistan', (SELECT id FROM continent WHERE name = 'Asia')),
('Panama', (SELECT id FROM continent WHERE name = 'North America')),
('Peru', (SELECT id FROM continent WHERE name = 'South America')),
('Philippines', (SELECT id FROM continent WHERE name = 'Asia')),
('Palau', (SELECT id FROM continent WHERE name = 'Oceania')),
('Papua New Guinea', (SELECT id FROM continent WHERE name = 'Oceania')),
('Poland', (SELECT id FROM continent WHERE name = 'Europe')),
('Puerto Rico', (SELECT id FROM continent WHERE name = 'North America')),
('Korea, Democratic People''s Republic of', (SELECT id FROM continent WHERE name = 'Asia')),
('Portugal', (SELECT id FROM continent WHERE name = 'Europe')),
('Paraguay', (SELECT id FROM continent WHERE name = 'South America')),
('Palestine, State of', (SELECT id FROM continent WHERE name = 'Asia')),
('French Polynesia', (SELECT id FROM continent WHERE name = 'Oceania')),
('Qatar', (SELECT id FROM continent WHERE name = 'Asia')),
('R�union', (SELECT id FROM continent WHERE name = 'Africa')),
('Romania', (SELECT id FROM continent WHERE name = 'Europe')),
('Russian Federation', (SELECT id FROM continent WHERE name = 'Europe')),
('Rwanda', (SELECT id FROM continent WHERE name = 'Africa')),
('Saudi Arabia', (SELECT id FROM continent WHERE name = 'Asia')),
('Sudan', (SELECT id FROM continent WHERE name = 'Africa')),
('Senegal', (SELECT id FROM continent WHERE name = 'Africa')),
('Singapore', (SELECT id FROM continent WHERE name = 'Asia')),
('South Georgia and the South Sandwich Islands', (SELECT id FROM continent WHERE name = 'South America')),
('Saint Helena, Ascension and Tristan da Cunha', (SELECT id FROM continent WHERE name = 'Africa')),
('Svalbard and Jan Mayen', (SELECT id FROM continent WHERE name = 'Europe')),
('Solomon Islands', (SELECT id FROM continent WHERE name = 'Oceania')),
('Sierra Leone', (SELECT id FROM continent WHERE name = 'Africa')),
('El Salvador', (SELECT id FROM continent WHERE name = 'North America')),
('San Marino', (SELECT id FROM continent WHERE name = 'Europe')),
('Somalia', (SELECT id FROM continent WHERE name = 'Africa')),
('Saint Pierre and Miquelon', (SELECT id FROM continent WHERE name = 'North America')),
('Serbia', (SELECT id FROM continent WHERE name = 'Europe')),
('South Sudan', (SELECT id FROM continent WHERE name = 'Africa')),
('Sao Tome and Principe', (SELECT id FROM continent WHERE name = 'Africa')),
('Suriname', (SELECT id FROM continent WHERE name = 'South America')),
('Slovakia', (SELECT id FROM continent WHERE name = 'Europe')),
('Slovenia', (SELECT id FROM continent WHERE name = 'Europe')),
('Sweden', (SELECT id FROM continent WHERE name = 'Europe')),
('Eswatini', (SELECT id FROM continent WHERE name = 'Africa')),
('Seychelles', (SELECT id FROM continent WHERE name = 'Africa')),
('Syrian Arab Republic', (SELECT id FROM continent WHERE name = 'Asia')),
('Turks and Caicos Islands', (SELECT id FROM continent WHERE name = 'North America')),
('Chad', (SELECT id FROM continent WHERE name = 'Africa')),
('Togo', (SELECT id FROM continent WHERE name = 'Africa')),
('Thailand', (SELECT id FROM continent WHERE name = 'Asia')),
('Tajikistan', (SELECT id FROM continent WHERE name = 'Asia')),
('Tokelau', (SELECT id FROM continent WHERE name = 'Oceania')),
('Turkmenistan', (SELECT id FROM continent WHERE name = 'Asia')),
('Tonga', (SELECT id FROM continent WHERE name = 'Oceania')),
('Trinidad and Tobago', (SELECT id FROM continent WHERE name = 'North America')),
('Tunisia', (SELECT id FROM continent WHERE name = 'Africa')),
('Turkey', (SELECT id FROM continent WHERE name = 'Asia')),
('Tuvalu', (SELECT id FROM continent WHERE name = 'Oceania')),
('Taiwan, Province of China', (SELECT id FROM continent WHERE name = 'Asia')),
('Tanzania, United Republic of', (SELECT id FROM continent WHERE name = 'Africa')),
('Uganda', (SELECT id FROM continent WHERE name = 'Africa')),
('Ukraine', (SELECT id FROM continent WHERE name = 'Europe')),
('Uruguay', (SELECT id FROM continent WHERE name = 'South America')),
('United States', (SELECT id FROM continent WHERE name = 'North America')),
('Uzbekistan', (SELECT id FROM continent WHERE name = 'Asia')),
('Saint Vincent and the Grenadines', (SELECT id FROM continent WHERE name = 'North America')),
('Venezuela, Bolivarian Republic of', (SELECT id FROM continent WHERE name = 'South America')),
('Virgin Islands, British', (SELECT id FROM continent WHERE name = 'North America')),
('Virgin Islands, U.S.', (SELECT id FROM continent WHERE name = 'North America')),
('Viet Nam', (SELECT id FROM continent WHERE name = 'Asia')),
('Vanuatu', (SELECT id FROM continent WHERE name = 'Oceania')),
('Wallis and Futuna', (SELECT id FROM continent WHERE name = 'Oceania')),
('Samoa', (SELECT id FROM continent WHERE name = 'Oceania')),
('Yemen', (SELECT id FROM continent WHERE name = 'Asia')),
('South Africa', (SELECT id FROM continent WHERE name = 'Africa')),
('Zambia', (SELECT id FROM continent WHERE name = 'Africa')),
('Zimbabwe', (SELECT id FROM continent WHERE name = 'Africa')),
('Unknown', (SELECT id FROM continent WHERE name = 'Unknown')),
('Multiple', (SELECT id FROM continent WHERE name = 'Unknown'))
ON CONFLICT (name) DO NOTHING;

-- Seed the vendor table
INSERT INTO vendor (name, currency_code_id, country_id) VALUES
('Traffic Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Eight Ounce Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Revolver Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada'))
ON CONFLICT (name) DO NOTHING;
