INSERT INTO continent (name) VALUES
('Africa'),
('Antarctica'),
('Asia'),
('Europe'),
('North America'),
('Oceania'),
('South America'),
('Unknown')
ON CONFLICT (name) DO NOTHING;

-- Seed the `currency_code` table
INSERT INTO currency_code (code) VALUES
('CAD'),
('USD')
ON CONFLICT (code) DO NOTHING;

-- Seed the country table
INSERT INTO country (name, continent_id) VALUES
('Burundi', (SELECT id FROM continent WHERE name = 'Africa')),
('Bolivia', (SELECT id FROM continent WHERE name = 'South America')),
('Brazil', (SELECT id FROM continent WHERE name = 'South America')),
('Canada', (SELECT id FROM continent WHERE name = 'North America')),
('Chile', (SELECT id FROM continent WHERE name = 'South America')),
('China', (SELECT id FROM continent WHERE name = 'Asia')),
('Congo', (SELECT id FROM continent WHERE name = 'Africa')),
('Colombia', (SELECT id FROM continent WHERE name = 'South America')),
('Costa Rica', (SELECT id FROM continent WHERE name = 'North America')),
('Ecuador', (SELECT id FROM continent WHERE name = 'South America')),
('Ethiopia', (SELECT id FROM continent WHERE name = 'Africa')),
('United Kingdom', (SELECT id FROM continent WHERE name = 'Europe')),
('Guinea', (SELECT id FROM continent WHERE name = 'Africa')),
('Guatemala', (SELECT id FROM continent WHERE name = 'North America')),
('Honduras', (SELECT id FROM continent WHERE name = 'North America')),
('Indonesia', (SELECT id FROM continent WHERE name = 'Asia')),
('India', (SELECT id FROM continent WHERE name = 'Asia')),
('Kenya', (SELECT id FROM continent WHERE name = 'Africa')),
('Mexico', (SELECT id FROM continent WHERE name = 'North America')),
('Myanmar', (SELECT id FROM continent WHERE name = 'Asia')),
('Nicaragua', (SELECT id FROM continent WHERE name = 'North America')),
('Panama', (SELECT id FROM continent WHERE name = 'North America')),
('Peru', (SELECT id FROM continent WHERE name = 'South America')),
('Philippines', (SELECT id FROM continent WHERE name = 'Asia')),
('Papua New Guinea', (SELECT id FROM continent WHERE name = 'Oceania')),
('Paraguay', (SELECT id FROM continent WHERE name = 'South America')),
('Rwanda', (SELECT id FROM continent WHERE name = 'Africa')),
('El Salvador', (SELECT id FROM continent WHERE name = 'North America')),
('Thailand', (SELECT id FROM continent WHERE name = 'Asia')),
('Tunisia', (SELECT id FROM continent WHERE name = 'Africa')),
('Tanzania', (SELECT id FROM continent WHERE name = 'Africa')),
('United States', (SELECT id FROM continent WHERE name = 'North America')),
('Yemen', (SELECT id FROM continent WHERE name = 'Asia')),
('South Africa', (SELECT id FROM continent WHERE name = 'Africa')),
('Unknown', (SELECT id FROM continent WHERE name = 'Unknown')),
('Multiple', (SELECT id FROM continent WHERE name = 'Unknown'))
ON CONFLICT (name) DO NOTHING;

INSERT INTO vendor (name, currency_code_id, country_id) VALUES
('Black Creek Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Continuum Coffee Roasters', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('De Mello', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Heart Coffee Roasters', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('House of Funk Brewing', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Library Specialty Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Luna Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Matchstick', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Monogram Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Nemesis Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Pallet Coffee Roasters', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Phil & Sebastian', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Pirates of Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Prairie Lily Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Quietly Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Rabbit Hole Roasters', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Rosso Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Sam James Coffee Bar', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('September Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Sey Coffee', (SELECT id FROM currency_code WHERE code = 'USD'), (SELECT id FROM country WHERE name = 'United States')),
('Sorellina Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Subtext Coffee Roasters', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('The Angry Roaster', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Thom Bargen Coffee Roasters', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Transcend Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Zab Café', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Rogue Wave Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Hatch Coffee Roasters', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Prototype Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Timbertrain Coffee Roasters', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Traffic Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Eight Ounce Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada')),
('Revolver Coffee', (SELECT id FROM currency_code WHERE code = 'CAD'), (SELECT id FROM country WHERE name = 'Canada'))
ON CONFLICT (name) DO NOTHING;